Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using ThuongMaiDienTu.Data;
using ThuongMaiDienTu.ViewModel;
using ThuongMaiDienTu.Helper;
using Microsoft.AspNetCore.Authorization;
using ThuongMaiDienTu.Service;
using PayPalCheckoutSdk.Core;

namespace ThuongMaiDienTu.Controllers
{
    public class CartController : Controller
    {
        private readonly IVnPayService _vnPayService;
        private readonly PaypalClient _paypalClient;
        private readonly Hshop2023Context _contex;


        public CartController(Hshop2023Context context, PaypalClient paypalClient, IVnPayService vnPayService)
        {
            _vnPayService = vnPayService;
            _paypalClient = paypalClient;
            _contex = context;
        }
        public List<CartItem> Cart => HttpContext.Session.Get<List<CartItem>>(MySetting.CART_KEY) ?? new List<CartItem>();
        public IActionResult Index()
        {

            return View(Cart);
        }

        public IActionResult AddToCart(int id, int quantity = 1)
        {
            var cart = Cart;

            var item = cart.SingleOrDefault(x => x.Id == id);
            if (item == null)
            {
                var hh = _contex.HangHoas.SingleOrDefault(p => p.MaHh == id);
                if (hh == null)
                {
                    TempData["Message"] = $"Không tìm thấy hàng hóa có mã {id}";
                    return NotFound();
                }

                item = new CartItem
                {
                    Id = hh.MaHh,
                    Image = hh.Hinh ?? string.Empty,
                    Quantity = quantity,
                    Name = hh.TenHh,
                    Price = hh.DonGia ?? 0,
                    Discout = hh.GiamGia
                };
                cart.Add(item);
            }
            else
            {
                item.Quantity += quantity;
            }
            HttpContext.Session.Set(MySetting.CART_KEY, cart);
            return RedirectToAction("Index");
        }
        public IActionResult RemoveToCart(int id)
        {
            var cart = Cart;

            var item = cart.SingleOrDefault(x => x.Id == id);
            if (item == null)
            {
                var hh = _contex.HangHoas.SingleOrDefault(p => p.MaHh == id);
                if (hh == null)
                {
                    return RedirectToAction("Index", "HomeController");
                }
                return RedirectToAction("Index", "HomeController");

            }
            else {
                cart.Remove(item);
            }

            HttpContext.Session.Set(MySetting.CART_KEY, cart);
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Customer")]
        [HttpGet]
        public IActionResult CheckOut()
        {


            if (Cart.Count() == 0)
            {
                return Redirect("/");
            }
            ViewBag.PaypalClientId = _paypalClient.ClientId;

            return View(Cart);
        }
        [Authorize(Roles = "Customer")]
        [HttpPost]
        public IActionResult CheckOut(CheckOutVM model, string payment = PaymentType.COD)
        {

            if (ModelState.IsValid)
            { if (!model.SameCustomer)
                {
                    if (model.Name == null || model.Phone == null || model.Address == null)
                    {
                        ModelState.AddModelError("error", "information is not empty");
                        return View(Cart);

                    }
                }
                var _paymentModel = new PaymentsModel
                {
                    CachThanhToan = "",
                    CachVanChuyen = "",
                    MaTrangThai = 0  //Unpaid
                };

                if (payment == "Place Order By VNPAY")
                {
                    var VnpayModel = new VnPaymentResquesModel
                    {
                        Amount = Cart.Sum(p => p.Total),
                        CreateDate = DateTime.Now,
                        Description = $"{model.Name} {model.Phone}",
                        fullname = model.Name,

                    };
                    _paymentModel.CachVanChuyen = "Local";
                    _paymentModel.CachThanhToan = "VNPAY";

                    var ad = AddOrder(model, _paymentModel);
                    if (ad != 0 && ad != -1)
                    {
                        VnpayModel.orderId = ad;
                        return Redirect(_vnPayService.CreatePaymentUrl(HttpContext, VnpayModel));

                    }
                    return View("fail");
                }
                _paymentModel.CachVanChuyen = "Local";
                _paymentModel.CachThanhToan = "COD";
                var _add_order = AddOrder(model, _paymentModel);
                if (_add_order == -1)
                {
                    return View("Fail");
                }
                if (_add_order == 0)
                {
                    return View(Cart);

                }
                return View("Success");

            }
            return View(Cart);
        }
        [Authorize(Roles = "Customer")]
        public IActionResult PaymentFail()
        {
            return View("fail");
        }
        [Authorize(Roles = "Customer")]
        public IActionResult PaymentSuccess()
        {
            return View("Success");
        }
        [Authorize(Roles = "Customer")]

        public IActionResult PaymentCallBack()
        {
            var response = _vnPayService.PaymentExcute(Request.Query);
            var HD = _contex.HoaDons.FirstOrDefault(p => p.MaHd == response.OrderId);

            if (response == null || response.VnPayResponseCode != "00")
            {
                TempData["Message"] = $"Lỗi Thanh Toán VNPAY: {response.VnPayResponseCode}";
                HD.MaTrangThai = -1;// lỗi thanh toán 
                _contex.SaveChanges();
                return RedirectToAction("PaymentFail");
            }
            HD.MaTrangThai = 1;
            _contex.SaveChanges();
            TempData["Message"] = $"Thanh Toán VNPAY Thành Công";
            return RedirectToAction("PaymentSuccess");

        }
        public int AddOrder(CheckOutVM model, PaymentsModel PModel)
        {
            var ghichu = model.Note;
            var CustomerId = HttpContext.User.Claims.SingleOrDefault(Cu => Cu.Type == MySetting.CLAIMS_CUSTOMERID).Value;
            var KH = new KhachHang();
            if(model.SameCustomer)
            {
                model = new CheckOutVM();
                KH = _contex.KhachHangs.SingleOrDefault(Kh => Kh.MaKh == CustomerId);

            }
            var HoaDon = new HoaDon()
            {
                MaKh = CustomerId ?? KH.MaKh,
                HoTen = model.Name ?? KH.HoTen,
                DiaChi = model.Address ?? KH.DiaChi,
                SoDienThoai = model.Phone ?? KH.DienThoai,
                NgayDat = DateTime.Now,
                CachThanhToan = PModel.CachThanhToan,
                CachVanChuyen = PModel.CachVanChuyen,
                MaTrangThai = PModel.MaTrangThai,
                GhiChu = ghichu


            };
            //_contex.HoaDons.Add(HoaDon);
            _contex.Database.BeginTransaction();
            try
            {

                _contex.Database.CommitTransaction();
                _contex.Add(HoaDon);
                _contex.SaveChanges();

                var Details = new List<ChiTietHd>();
                foreach (var item in Cart)
                {
                    if (item == null)
                    {
                        return -1;//error
                    }
                    Details.Add(new ChiTietHd
                    {
                        MaHd = HoaDon.MaHd,
                        SoLuong = item.Quantity,
                        DonGia = item.Price - (item.Price * item.Discout),
                        MaHh = item.Id,
                        GiamGia = item.Discout,

                    });
                }
                _contex.AddRange(Details);
                _contex.SaveChanges();
                HttpContext.Session.Set<List<CartItem>>(MySetting.CART_KEY, new List<CartItem>());
                return HoaDon.MaHd;//success

            }
            catch (Exception ex)
            {
                _contex.Database.RollbackTransaction();
                return 0;

            }
        }
        #region PaypalPayment
        [Authorize(Roles = "Customer")]
        [HttpPost("/Cart/create-paypal-order")]
        public async Task<IActionResult> CreatePaypalOrder(CancellationToken cancellationToken)
        {
            var TotalPrice=Cart.Sum(x => x.Total).ToString();
            var currency = "USD";
            var reference = "DH" + DateTime.Now.Ticks.ToString();
            try
            {
                var response = await _paypalClient.CreateOrder(TotalPrice, currency, reference);
                return Ok(response);
            }
            catch(Exception e) {
             var error = new {e.GetBaseException().Message};
                return BadRequest(error);
            }
        }
        [Authorize(Roles = "Customer")]
        [HttpPost("/Cart/capture-paypal-order")]
        public async Task<IActionResult> CapturePayPalOrder(string orderID,[FromBody]CheckOutVM model,CancellationToken cancellationToken)
        {
            try
            {
                var response = await _paypalClient.CaptureOrder(orderID);
                if(orderID=="0")
                {
                    return RedirectToAction("PaymentFail");
                }
                var _paymentModel = new PaymentsModel
                {
                    CachThanhToan="PayPal",
                    CachVanChuyen="local",
                    MaTrangThai=1
                };

                var add_db = AddOrder(model, _paymentModel);
                if (add_db != 0 && add_db != -1)
                {

Controllers/HangHoaController.cs
using Microsoft.AspNetCore.Mvc;
using ThuongMaiDienTu.Data;
using ThuongMaiDienTu.ViewModel;
using X.PagedList;
using X.PagedList.Extensions;

namespace ThuongMaiDienTu.Controllers
{
    public class HangHoaController : Controller
    {
        private readonly Hshop2023Context _context;
        private const int PageSize = 6;

        public HangHoaController(Hshop2023Context context) =>_context=context;
        public IActionResult Index(int? loai,int?page=1)
        {
            if(loai==0)
            {
                loai = null;
            }    
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
            var hh=_context.HangHoas.AsQueryable();
            if (loai.HasValue)
            {
                hh = hh.Where(p => p.MaLoai == loai.Value).OrderBy(x=>x.TenHh);
            }
            var result = hh.Select(p => new HangHoaVM
            {
                Id = p.MaHh,
                Name = p.TenHh,
                Image = p.Hinh ,
                Discout=p.GiamGia,
                Price=p.DonGia ??0,
                CateID=loai??0

            }).ToPagedList(pageNumber,PageSize);
            return View(result);
        }
        public IActionResult Search(string? query, double? minPrice, double? maxPrice, string?OrderByName,string?OrderByPrice, int?page=1)
        {
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
            var hh = _context.HangHoas.AsQueryable();
            if (minPrice.HasValue)
            {
                hh = hh.Where(p => p.DonGia >= minPrice.Value);
            }

            if (maxPrice.HasValue)
            {
                hh = hh.Where(p => p.DonGia <= maxPrice.Value);
            }
            if(!string.IsNullOrEmpty(query))
            {
               hh= hh.Where(p => p.TenHh.Contains(query));
            }
            if (!string.IsNullOrEmpty(OrderByPrice))
            {
                hh = hh.OrderBy(x=>x.DonGia);
            }
            if (!string.IsNullOrEmpty(OrderByName))
            {
                hh = hh.OrderBy(x => x.TenHh);
            }
            var result = hh.Select(p => new HangHoaVM
            {
                Id = p.MaHh,
                Name = p.TenHh,
                Image = p.Hinh,
                Discout = p.GiamGia,
                Price = p.DonGia ?? 0,

            }).ToPagedList(pageNumber, PageSize);
            ViewBag.query = query;
            ViewBag.minPrice = minPrice;
            ViewBag.maxPrice = maxPrice;

            return View(result);
        }
        public IActionResult Detail(int id) {
            var data = _context.HangHoas.SingleOrDefault(p => p.MaHh == id);
            if (data == null)
            {
               return NotFound();
            }
            var result = new HangHoaDetailVM
            {
                Id = data.MaHh,    
                Name = data.TenHh,
                Price=data.DonGia??0,
                Description=data.MoTa??string.Empty,
                ShortDescription = data.MoTaDonVi ?? string.Empty,
                Discout =data.GiamGia,
                Review=5,
                Image=data.Hinh??string.Empty,
                QuantityInStock=10

            };
            return View(result);
        }
    }
}

Views/HangHoa/Index.cshtml
@* @model IEnumerable<ThuongMaiDienTu.ViewModel.HangHoaVM> *@
@using X.PagedList.Extensions
@model X.PagedList.IPagedList<ThuongMaiDienTu.ViewModel.HangHoaVM>
@{
    ViewData["Title"] = "Index";
    Layout = "_DanhSachHangHoa";
}
 <!-- Breadcrumb Start -->
 @section BreadCum{
<div class="container-fluid"> 
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <a class="breadcrumb-item text-dark" href="#">Shop</a>
                <span class="breadcrumb-item active">Shop List</span>
            </nav>
        </div>
    </div>
</div>
 }
<!-- Breadcrumb End -->
<!-- Shop Start -->
@await Html.PartialAsync("ProductItem",Model)
<div class="col-12">
    <nav>
        <div class="pagination justify-content-center">
            @{
                var item = Model[0]??null;
            }
            <div class="pagination">
                @if (Model.HasPreviousPage)
                {
                    <a class="page-link" href="@Url.Action("Index", new { loai=item.CateID??null,page = Model.PageNumber - 1 })">Previous</a>
                }

                @for (int i = 1; i <= Model.PageCount; i++)
                {
                    <a href="@Url.Action("Index", new { loai=item.CateID??null,page = i })" class="page-link">@i</a>
                }

                @if (Model.HasNextPage)
                {
                    <a class="page-link" href="@Url.Action("Index", new { loai=item.CateID??null,page = Model.PageNumber + 1 })">Next</a>
                }
            </div>


        </div>
    </nav>
</div>
<!-- Shop End -->

Views/HangHoa/ProductItem.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model X.PagedList.IPagedList<ThuongMaiDienTu.ViewModel.HangHoaVM>
<div class="col-12 pb-1">
    <h3><b>Have @Model.TotalItemCount Products.</b></h3>
</div>
@foreach (var item in Model)
{
    <div class="col-lg-4 col-md-6 col-sm-6 pb-1">
        <div class="product-item bg-light mb-4">
            <a asp-action="Detail" asp-controller="HangHoa" asp-route-id="@item.Id"></a>
            <div class="product-img position-relative overflow-hidden">
                <img class="img-fluid w-100" src="~/Hinh/HangHoa/@item.Image" alt="@item.Name">
                <div class="product-action">
                    <a class="btn btn-outline-dark btn-square" asp-action="AddToCart" asp-controller="Cart" asp-route-id="@item.Id"><i class="fa fa-shopping-cart"></i></a>
                    <a class="btn btn-outline-dark btn-square" href=""><i class="far fa-heart"></i></a>
                    <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-sync-alt"></i></a>
                    <a class="btn btn-outline-dark btn-square" asp-action="Detail" asp-controller="HangHoa" asp-route-id="@item.Id"><i class="fa fa-search"></i></a>
                </div>
            </div>
            <div class="text-center py-4">
                <a class="h6 text-decoration-none text-truncate" asp-action="Detail" asp-controller="HangHoa" asp-route-id="@item.Id">@item.Name</a>
                <div class="d-flex align-items-center justify-content-center mt-2">
                    <h5>@(item.Price - (item.Discout * item.Price))$</h5><h6 class="text-muted ml-2"><del>@item.Price$</del></h6>
                </div>
                <div class="d-flex align-items-center justify-content-center mb-1">
                    <small class="fa fa-star text-primary mr-1"></small>
                    <small class="fa fa-star text-primary mr-1"></small>
                    <small class="fa fa-star text-primary mr-1"></small>
                    <small class="fa fa-star text-primary mr-1"></small>
                    <small class="fa fa-star text-primary mr-1"></small>
                    <small>(99)</small>
                </div>
            </div>
        </div>
    </div>
}

Views/HangHoa/Search.cshtml
@model X.PagedList.IPagedList<ThuongMaiDienTu.ViewModel.HangHoaVM>
@{
    ViewData["Title"] = "Search";
    Layout = "_DanhSachHangHoa";
}

<!-- Shop Start -->
@await Html.PartialAsync("ProductItem", Model)
<div class="col-12">
    <nav>
        <div class="pagination justify-content-center">
           
            <div class="pagination">
                @if (Model.HasPreviousPage)
                {
                    <a class="page-link" href="@Url.Action("Search", new {query=ViewBag.query,ViewBag.minPrice,ViewBag.maxPrice, page = Model.PageNumber - 1 })">Previous</a>
                }

                @for (int i = 1; i <= Model.PageCount; i++)
                {
                    <a href="@Url.Action("Search", new { query=ViewBag.query,ViewBag.minPrice,ViewBag.maxPrice,page = i })" class="page-link">@i</a>
                }

                @if (Model.HasNextPage)
                {
                    <a class="page-link" href="@Url.Action("Search", new {query=ViewBag.query,ViewBag.minPrice,ViewBag.maxPrice, page = Model.PageNumber + 1 })">Next</a>
                }
            </div>


        </div>
    </nav>
</div>
<!-- Shop End -->