Areas/Admin/Controllers/HoaDonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThuongMaiDienTu.Data;
using ThuongMaiDienTu.ViewModel;
using X.PagedList.Extensions;

namespace ThuongMaiDienTu.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("admin/HoaDon")]
    [Authorize(Roles = "Admin")]

    public class HoaDonsController : Controller
    {
        private readonly Hshop2023Context _context;
        private const int pageSize =20;
        public HoaDonsController(Hshop2023Context context)
        {
            _context = context;
        }

        // GET: Admin/HoaDons
        [Route("")]
        public IActionResult Index(int? filter, int? page=1)
        {
            var data=_context.HoaDons.AsQueryable();
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
             data = data.Include(h => h.MaKhNavigation).Include(h => h.MaNvNavigation).Include(h => h.MaTrangThaiNavigation);
            if (filter.HasValue && filter != 100)
            {
                data = data.Where(x => x.MaTrangThai == filter);
            }
            var hd = data.Select(p => new HoadonVM
            {
                MaHd = p.MaHd,
                MaKh = p.MaKh,
                MaTrangThai = p.MaTrangThai,
                NgayDat = p.NgayDat,
                SoDienThoai = p.SoDienThoai,
                Ten=p.MaKhNavigation.HoTen??string.Empty,
                DiaChi=p.DiaChi,
                TongTien=_context.ChiTietHds.Where(x=>x.MaHd==p.MaHd).Sum(x=>(x.SoLuong*(x.DonGia-(x.DonGia*x.GiamGia))))           

            }).OrderByDescending(x => x.NgayDat).ToPagedList(pageNumber,pageSize);
            ViewBag.filter = filter;
            return View(hd);
        }
        [Route("FilterInvoices")]
        public IActionResult FilterInvoices(int? filter, int? page = 1)
        {
            var data = _context.HoaDons.AsQueryable();
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
            data = data.Include(h => h.MaKhNavigation).Include(h => h.MaNvNavigation).Include(h => h.MaTrangThaiNavigation);
            if (filter.HasValue&&filter!=100)
            {
                data = data.Where(x => x.MaTrangThai == filter);
            }
            var hd = data.Select(p => new HoadonVM
            {
                MaHd = p.MaHd,
                MaKh = p.MaKh,
                MaTrangThai = p.MaTrangThai,
                NgayDat = p.NgayDat,
                SoDienThoai = p.SoDienThoai,
                Ten = p.MaKhNavigation.HoTen ?? string.Empty,
                DiaChi = p.DiaChi,
                TongTien = _context.ChiTietHds.Where(x => x.MaHd == p.MaHd).Sum(x => (x.SoLuong * (x.DonGia - (x.DonGia * x.GiamGia))))

            }).OrderByDescending(x => x.NgayDat).ToPagedList(pageNumber, pageSize);
            ViewBag.filter = filter;

            return PartialView("HoaDonViewFilter", hd);
        }

        // GET: Admin/HoaDons/Details/5
        [Route("Details")]
        public  IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
             var data = _context.ChiTietHds.Include(h => h.MaHhNavigation).Include(h => h.MaHdNavigation).Where(p=>p.MaHd==id);
            if (data == null)
            {
                return NotFound();
            }
            var hdct = data.Select(p => new HoadonDetailVM {
                DonGia = p.DonGia,
                GiamGia = p.GiamGia,
                SoLuong = p.SoLuong,
                Ten = p.MaHhNavigation.TenHh ?? string.Empty,
                TongTien = p.SoLuong * (p.DonGia-(p.DonGia*p.GiamGia))
            });
           

            return View(hdct.ToList());
        }

        [Route("Done")]

        [HttpGet]
        public  IActionResult Done(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hd =  _context.HoaDons.FirstOrDefault(x=>x.MaHd==id);
            if (hd == null)
            {
                return NotFound();
            }
            hd.MaTrangThai = 3;
            _context.Update(hd);
            _context.SaveChanges();
            TempData["Message"] = "Cập nhật thành công ";
            return RedirectToAction("index");
        }

    }
}

Areas/Admin/Views/HoaDons/Details.cshtml
@model IEnumerable<ThuongMaiDienTu.ViewModel.HoadonDetailVM>
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<h1>Details</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr class="table-warning">
            <th>
                Tên
            </th>
            <th>
                Giá
            </th>
            <th>
                Số Lượng 
            </th>
            <th>
                Phần trăm giảm
            </th>
            <th>
                Tổng tiền
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                    @item.Ten
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DonGia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiamGia)
            </td>
            <td>
                    @item.TongTien$
            </td>
            <td>
               
            </td>
        </tr>
}
    </tbody>
    
</table>
            <a asp-action="Index">Back</a> 

Areas/Admin/Views/HoaDons/Edit.cshtml
@model ThuongMaiDienTu.Data.HoaDon

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<h1>Edit</h1>

<h4>HoaDon</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaHd" />
            <div class="form-group">
                <label asp-for="MaKh" class="control-label"></label>
                <select asp-for="MaKh" class="form-control" asp-items="ViewBag.MaKh"></select>
                <span asp-validation-for="MaKh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayDat" class="control-label"></label>
                <input asp-for="NgayDat" class="form-control" />
                <span asp-validation-for="NgayDat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayCan" class="control-label"></label>
                <input asp-for="NgayCan" class="form-control" />
                <span asp-validation-for="NgayCan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayGiao" class="control-label"></label>
                <input asp-for="NgayGiao" class="form-control" />
                <span asp-validation-for="NgayGiao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoTen" class="control-label"></label>
                <input asp-for="HoTen" class="form-control" />
                <span asp-validation-for="HoTen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDienThoai" class="control-label"></label>
                <input asp-for="SoDienThoai" class="form-control" />
                <span asp-validation-for="SoDienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label"></label>
                <input asp-for="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CachThanhToan" class="control-label"></label>
                <input asp-for="CachThanhToan" class="form-control" />
                <span asp-validation-for="CachThanhToan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CachVanChuyen" class="control-label"></label>
                <input asp-for="CachVanChuyen" class="form-control" />
                <span asp-validation-for="CachVanChuyen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhiVanChuyen" class="control-label"></label>
                <input asp-for="PhiVanChuyen" class="form-control" />
                <span asp-validation-for="PhiVanChuyen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaTrangThai" class="control-label"></label>
                <select asp-for="MaTrangThai" class="form-control" asp-items="ViewBag.MaTrangThai"></select>
                <span asp-validation-for="MaTrangThai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaNv" class="control-label"></label>
                <select asp-for="MaNv" class="form-control" asp-items="ViewBag.MaNv"></select>
                <span asp-validation-for="MaNv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GhiChu" class="control-label"></label>
                <input asp-for="GhiChu" class="form-control" />
                <span asp-validation-for="GhiChu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/HoaDons/HoaDonViewFilter.cshtml
@model X.PagedList.IPagedList<ThuongMaiDienTu.ViewModel.HoadonVM>
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"

<table class="table">
    <thead>
        <tr class="table-warning">
            <th>
                @Html.DisplayNameFor(model => model[0].MaKh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].NgayDat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].MaTrangThai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].SoDienThoai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Ten)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].DiaChi)
            </th>
            <th>
                Tổng Tiền
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var hh in Model)
        {
            <tr class="table-success">
                <td>
                    @Html.DisplayFor(modelItem => hh.MaKh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => hh.NgayDat)
                </td>
                <td>
                    @if (hh.MaTrangThai == 1)
                    {
                        <i>Đã thanh toán </i>
                    }

                    else
                    {
                        @if (hh.MaTrangThai == 0)
                        {

                            <i>Chưa thanh toán</i>
                        }
                        else
                        {
                            @if (hh.MaTrangThai == 3)
                            {
                                <i>Đã giao hàng</i>
                            }
                            else
                            {
                                <i>Thanh toán bị lỗi</i>
                            }

                        }
                    }

                </td>
                <td>
                    @Html.DisplayFor(modelItem => hh.SoDienThoai)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => hh.Ten)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => hh.DiaChi)
                </td>
                <td>
                    @hh.TongTien$
                </td>
                <td>@if(hh.MaTrangThai==3)
                    {
                    }
                    else{
                    <a asp-action="Done" asp-route-id="@hh.MaHd">Done</a>

                    }


                    <a asp-action="Details" asp-controller="HoaDons" asp-area="Admin" asp-route-id="@hh.MaHd">Details</a> 
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="pagination">
    @{
        var itemcout = 0;

    }
    @if (Model.HasPreviousPage)
    {
        var item = Model.PageNumber - 1;
        <a class="page-link" href="@Url.Action("index", new {ViewBag.filter , page = Model.PageNumber - 1 })">Previous</a>
        if (Model.PageNumber - 1 != 1)
        {
            item = item - 1;
            <a class="page-link" href="@Url.Action("index", new { ViewBag.filter,page = Model.PageNumber - 2 })">@item</a>
            item += 1;
        }
        <a class="page-link" href="@Url.Action("index", new {ViewBag.filter, page = Model.PageNumber - 1 })">@item</a>

    }

    @for (int i = Model.PageNumber; i <= Model.PageCount; i++)
    {
        if (itemcout < 6)
        {
            <a href="@Url.Action("index", new {ViewBag.filter, page = i })" class="page-link">@i</a>
            itemcout += 1;
        }
    }

    @if (Model.HasNextPage)
    {
        <a class="page-link" href="@Url.Action("index", new {ViewBag.filter, page = Model.PageNumber + 1 })">Next</a>
    }
</div>

Areas/Admin/Views/HoaDons/Index.cshtml
@model X.PagedList.IPagedList<ThuongMaiDienTu.ViewModel.HoadonVM>
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<h1>List Orders</h1>
<h2 class="text-danger  ">@TempData["Message"]</h2>
<form asp-action="Index" asp-controller="HoaDon">
    <div class="input-group">
        <input id="txt" type="text" class="form-control" placeholder="Search for orders" name="query">
       
        </div>
    <button type="submit" class="btn-danger">Search</button>
</form>
<div>
    <input type="radio" id="all" name="filter" value="100" checked />
    <label for="all">All</label>

    <input type="radio" id="paid" name="filter" value="1" />
    <label for="paid">Paid</label>

    <input type="radio" id="Completed" name="filter" value="3" />
    <label for="Completed">Completed </label>

    <input type="radio" id="Error" name="filter" value="-1" />
    <label for="Error">Error </label>
</div>
<div id="invoice-list">

    @Html.Partial("HoaDonViewFilter",Model)
</div>
@section Scripts {
    <script>

        $(document).ready(function () {
            $('input[type=radio][name=filter]').change(function () {
                var filter = $(this).val();

                $.ajax({
                    url: '@Url.Action("FilterInvoices", "HoaDons")',
                    type: 'GET',
                    data: { filter: filter },
                    success: function (result) {
                        $('#invoice-list').html(result);
                    }
                });
            });
        });
    </script>
}


    