Areas/Admin/Controllers/NhanViensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThuongMaiDienTu.Data;
using ThuongMaiDienTu.Helper;
using ThuongMaiDienTu.ViewModel;

namespace ThuongMaiDienTu.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("admin/Account")]
    public class NhanViensController : Controller
    {
        private readonly IMapper _mapper;
        private readonly Hshop2023Context _context;

        public NhanViensController(Hshop2023Context context,IMapper mapper)
        {
            _mapper=mapper;
            _context = context;
        }

        // GET: Admin/NhanViens
        [HttpGet]
        [Route("Index")]
        [Authorize(Roles = "Admin")]

        public IActionResult Index()
        {
            return View( _context.NhanViens.ToList());
        }

        // GET: Admin/NhanViens/Details/5
        //public async Task<IActionResult> Details(string id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var nhanVien = await _context.NhanViens
        //        .FirstOrDefaultAsync(m => m.MaNv == id);
        //    if (nhanVien == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(nhanVien);
        //}

        // GET: Admin/NhanViens/Create
        [Route("Create")]
        [Authorize(Roles = "Admin")]

        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/NhanViens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Create")]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(RegisterVM model, IFormFile? Hinh)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var NV = _mapper.Map<NhanVien>(model);
                    NV.MaNv = model.MaKh;
                    NV.RandomKey = Util.GenerateRandomKey();
                    NV.MatKhau = model.MatKhau.ToMd5Hash(NV.RandomKey);
                    NV.HieuLuc = true;//xu ly sau
                    NV.VaiTro = 0;
                    if (Hinh != null)
                    {
                        NV.Hinh = Util.UploadImage(Hinh, "NhanVien");
                    }
                    _context.NhanViens.Add(NV);
                    _context.SaveChanges();
                    TempData["Message"] = "Successfully";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    return NotFound();
                }

            }
            return View();
        }



        // GET: Admin/NhanViens/Edit/5
        [Route("Edit")]
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nhanVien = await _context.NhanViens.FindAsync(id);
            if (nhanVien == null)
            {
                return NotFound();
            }
            return View();
        }

        // POST: Admin/NhanViens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Edit")]
    [Authorize(Roles = "Admin")]


        //public async Task<IActionResult> Edit(string id, RegisterVM model, IFormFile? Hinh)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(nhanVien);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!NhanVienExists(nhanVien.MaNv))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(nhanVien);
        //}

        // GET: Admin/NhanViens/Delete/5
        [Route("Delete")]
        [Authorize(Roles = "Admin")]

        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nhanVien =  _context.NhanViens
                .FirstOrDefault(m => m.MaNv == id);
            if (nhanVien == null)
            {
                return NotFound();
            }
            nhanVien.HieuLuc = false;
            _context.Update(nhanVien);
            TempData["Message"] = "Successfully";
            return RedirectToAction(nameof(Index));
        }

        // POST: Admin/NhanViens/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(string id)
        //{
        //    var nhanVien = await _context.NhanViens.FindAsync(id);
        //    if (nhanVien != null)
        //    {
        //        _context.NhanViens.Remove(nhanVien);
        //    }

        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool NhanVienExists(string id)
        {
            return _context.NhanViens.Any(e => e.MaNv == id);
        }
        //[HttpGet]
        //[Route("register")]
        //public IActionResult Register()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public IActionResult Register(RegisterVM model, IFormFile? Hinh)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            var NV = _mapper.Map<NVachHang>(model);
        //            NV.RandomKey = Util.GenerateRandomKey();
        //            NV.MatNVau = model.MatNVau.ToMd5Hash(NV.RandomKey);
        //            NV.HieuLuc = true;//xu ly sau
        //            NV.VaiTro = 0;
        //            if (Hinh != null)
        //            {
        //                NV.Hinh = Util.UploadImage(Hinh, "NVachHang");
        //            }
        //            _context.NVachHangs.Add(NV);
        //            _context.SaveChanges();
        //            return RedirectToAction("Index", "HangHoa");
        //        }
        //        catch (Exception ex)
        //        {
        //            return NotFound();
        //        }

        //    }
        //    return View();
        //}
        [HttpGet]
        [Route("login")]
        public IActionResult Login(string? ReturnUrl)
        {
            ViewBag.ReturnUrl = ReturnUrl;
            return View();
            
        }
        [Route("login")]
        [HttpPost]
        public async Task<IActionResult> Login(LoginVm model, string? ReturnUrl)
        {
            ViewBag.ReturnUrl = ReturnUrl;
            if (ModelState.IsValid)
            {
                var NV = _context.NhanViens.SingleOrDefault(nv => nv.MaNv == model.username);
                if (NV == null)
                {
                    ModelState.AddModelError("error", "wrong username or password");
                }
                else
                {
                    if (!NV.HieuLuc)
                    {
                        ModelState.AddModelError("error", "You cannot use this account anymore");
                    }
                    else
                    {
                        if (NV.MatKhau != model.password.ToMd5Hash(NV.RandomKey))
                        {
                            ModelState.AddModelError("error", "wrong username or password");

                        }
                        else
                        {
                            var claims = new List<Claim>()
                            {
                                new Claim(ClaimTypes.Email, NV.Email),
                                new Claim(ClaimTypes.Name, NV.HoTen),
                                new Claim(MySetting.CLAIMS_Admin, NV.MaNv),
								// động
								new Claim(ClaimTypes.Role, "Admin"),
                            };
                            var claimsIdentity = new ClaimsIdentity(claims, "login");
                            var claimsPrinciple = new ClaimsPrincipal(claimsIdentity);
                            await HttpContext.SignInAsync(claimsPrinciple);
                            HttpContext.Session.SetString("Admin", NV.HoTen);
                            if (Url.IsLocalUrl(ReturnUrl))
                            {
                                return Redirect(ReturnUrl);
                            }
                            else
                            {
                                return Redirect("/admin");
                            }

                        }
                    }
                }
            }
            return View();

        }
        [Authorize(Roles = "Admin")]
        [Route("LogOut")]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync();
            HttpContext.Session.Remove("Admin");


            return Redirect("/admin/account/login");
        }
    }
}

Areas/Admin/Views/NhanViens/Create.cshtml
@model ThuongMaiDienTu.ViewModel.RegisterVM
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<h1>Create</h1>

<h4>NhanVien</h4>
<hr />
<form asp-action="Create" asp-controller="NhanViens" asp-area="admin">
<div class="row">
	<div class="col-md-6 form-group">
		<label asp-for="@Model.MaKh"></label>
		<input class="form-control" asp-for="@Model.MaKh">
		<span asp-validation-for="@Model.MaKh" class="text-danger"></span>
	</div>
	<div class="col-md-6 form-group">
		<label asp-for="@Model.MatKhau"></label>
		<input class="form-control" asp-for="@Model.MatKhau">
		<span asp-validation-for="@Model.MatKhau" class="text-danger"></span>
	</div>
	<div class="col-md-6 form-group">
		<label asp-for="@Model.Email"></label>
		<input class="form-control" asp-for="@Model.Email">
		<span asp-validation-for="@Model.Email" class="text-danger"></span>
	</div>
	<div class="col-md-6 form-group">
		<label asp-for="@Model.HoTen"></label>
		<input class="form-control" asp-for="@Model.HoTen">
		<span asp-validation-for="@Model.HoTen" class="text-danger"></span>
	</div>
	<div class="col-md-6 form-group">
		<label asp-for="@Model.NgaySinh"></label>
		<input class="form-control" asp-for="@Model.NgaySinh">
		<span asp-validation-for="@Model.NgaySinh" class="text-danger"></span>
	</div>
	<div class="col-md-6 form-group">
		<label asp-for="@Model.DiaChi"></label>
		<input class="form-control " asp-for="@Model.DiaChi">
		<span asp-validation-for="@Model.DiaChi" class="text-danger"></span>
	</div>
	<div class="form-check col-md-6 " style="margin-left:4%;">
		<input class="form-check-input ml-auto " asp-for="@Model.GioiTinh">
		<label class="form-check-label ml-3" for="Sex">Men?</label>
	</div>
	<div class="col-md-6 form-group">
		<label asp-for="@Model.DienThoai"></label>
		<input class="form-control" asp-for="@Model.DienThoai">
		<span asp-validation-for="@Model.DienThoai" class="text-danger"></span>
	</div>
	<div class="col-md-6 form-group">
		<label asp-for="@Model.Hinh"></label>
		<input class="form-control" type="file" name="Hinh">
		<span asp-validation-for="@Model.Hinh" class="text-danger"></span>
	</div>
	<button type="submit" class="btn btn-block btn-primary font-weight-bold py-3">Register</button>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/NhanViens/Delete.cshtml
@model ThuongMaiDienTu.Data.NhanVien

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NhanVien</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HoTen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MatKhau)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiaChi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DienThoai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DienThoai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HieuLuc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HieuLuc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VaiTro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VaiTro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RandomKey)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RandomKey)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MaNv" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Areas/Admin/Views/NhanViens/Details.cshtml
@model ThuongMaiDienTu.Data.NhanVien

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<h1>Details</h1>

<div>
    <h4>NhanVien</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HoTen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MatKhau)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiaChi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DienThoai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DienThoai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HieuLuc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HieuLuc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VaiTro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VaiTro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RandomKey)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RandomKey)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MaNv">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/NhanViens/Edit.cshtml
@* @model ThuongMaiDienTu.ViewModel.RegisterVM
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<h1>Edit</h1>

<h4>NhanVien</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaNv" />
            <div class="form-group">
                <label asp-for="HoTen" class="control-label"></label>
                <input asp-for="HoTen" class="form-control" />
                <span asp-validation-for="HoTen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MatKhau" class="control-label"></label>
                <input asp-for="MatKhau" class="form-control" />
                <span asp-validation-for="MatKhau" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="GioiTinh" /> @Html.DisplayNameFor(model => model.GioiTinh)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="NgaySinh" class="control-label"></label>
                <input asp-for="NgaySinh" class="form-control" />
                <span asp-validation-for="NgaySinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label"></label>
                <input asp-for="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DienThoai" class="control-label"></label>
                <input asp-for="DienThoai" class="form-control" />
                <span asp-validation-for="DienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hinh" class="control-label"></label>
                <input asp-for="Hinh" class="form-control" />
                <span asp-validation-for="Hinh" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="HieuLuc" /> @Html.DisplayNameFor(model => model.HieuLuc)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="VaiTro" class="control-label"></label>
                <input asp-for="VaiTro" class="form-control" />
                <span asp-validation-for="VaiTro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RandomKey" class="control-label"></label>
                <input asp-for="RandomKey" class="form-control" />
                <span asp-validation-for="RandomKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

 *@

Areas/Admin/Views/NhanViens/Index.cshtml
@model IEnumerable<ThuongMaiDienTu.Data.NhanVien>
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<h1>Index</h1>
<h2 class="text-danger">@TempData["Message"]</h2>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.HoTen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MatKhau)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GioiTinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgaySinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DiaChi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DienThoai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HieuLuc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VaiTro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RandomKey)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HoTen)
                
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MatKhau)
            </td>
            <td>
                @if(item.GioiTinh==true)
                {
                  <p>Nam</p>  
                }
                else{

                        <p>Nữ</p>

                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgaySinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DienThoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hinh)
            </td>
            <td>
                    @if(item.HieuLuc == true)
                    {
                        <p>Đang hoạt động</p>

                    }
                    else
                    {

                        <p>Dừng hoạt động</p>

                    }
                </td>
            <td>
                    @Html.DisplayFor(modelItem => item.VaiTro)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RandomKey)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MaNv">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.MaNv">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.MaNv">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Areas/Admin/Views/NhanViens/login.cshtml
@{
    ViewData["Title"] = "Login";
    Layout = "~/Areas/Admin/Views/Shared/_LayputAuthen.cshtml";
}
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
@model ThuongMaiDienTu.ViewModel.LoginVm

<div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth">
            <div class="row flex-grow">
                <div class="col-lg-4 mx-auto">
                    <div class="auth-form-light text-left p-5">
                        <div class="brand-logo">
                            <img src="~/LayoutAdmin/assets/images/logo.svg">
                        </div>
                        <h4>Hello! let's get started</h4>
                        <h6 class="font-weight-light">Sign in to continue.</h6>
                        <form asp-action="login"  asp-route-returnurl="@ViewBag.ReturnUrl">
                            <div class="text-danger" asp-validation-summary="All"></div>
                            <div class="form-group">
                                <label asp-for="@Model.username"></label>
                                <input class="form-control form-control-lg" asp-for="@Model.username">
                                <span asp-validation-for="@Model.username" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="@Model.password"></label>
                                <input class="form-control form-control-lg" asp-for="@Model.password">
                                <span asp-validation-for="@Model.password" class="text-danger"></span>
                            </div>
                            <div class="mt-3">
                                <button type="submit"  class="btn btn-block btn-gradient-primary btn-lg font-weight-medium auth-form-btn" >SIGN IN</button>
                            </div>
                            <div class="my-2 d-flex justify-content-between align-items-center">
                                @* <div class="form-check">
                                    <label class="form-check-label text-muted">
                                        <input type="checkbox" class="form-check-input"> Keep me signed in
                                    </label>
                                </div> *@
                                <a href="#" class="auth-link text-black">Forgot password?</a>
                            </div>
                           @*  <div class="mb-2">
                                <button type="button" class="btn btn-block btn-facebook auth-form-btn">
                                    <i class="mdi mdi-facebook me-2"></i>Connect using facebook
                                </button>
                            </div> *@
                          
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
</div>